### ISSUE TITLE
add nodejs metrics

### ISSUE THREAD

**Issue by wemeetagain** [libp2p/js-libp2p-amino-dht-bootstrapper#138]
- https://github.com/siimon/prom-client?tab=readme-ov-file#default-metrics
- https://github.com/SimenB/node-prometheus-gc-stats

**Comment by SgtPooki** [comment]
we do collect default metrics already because `@libp2p/metrics-prometheus` does this by default: https://github.com/libp2p/js-libp2p/blob/b0c068196b890eb03583e2ba07b6b6350c66c480/packages/metrics-prometheus/src/index.ts#L90-L94

I can add node-prometheus-gc-stats too
